/**
 * News Feed
 * news feed api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: media@glennengstrand.info
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */

package info.glennengstrand.news.api

import info.glennengstrand.news.model.Outbound

import java.io.File

import org.scalatra.ScalatraServlet
import org.scalatra.swagger._
import org.json4s._
import org.json4s.JsonDSL._
import org.scalatra.json.{ JValueResult, JacksonJsonSupport }
import org.scalatra.servlet.{ FileUploadSupport, MultipartConfig, SizeConstraintExceededException }

import scala.collection.JavaConverters._
import info.glennengstrand.news.DI._

class OutboundApi(implicit val swagger: Swagger) extends ScalatraServlet
  with FileUploadSupport
  with JacksonJsonSupport
  with SwaggerSupport {
  protected implicit val jsonFormats: Formats = DefaultFormats

  protected val applicationDescription: String = "OutboundApi"

  before() {
    contentType = formats("json")
    response.headers += ("Access-Control-Allow-Origin" -> "*")
  }

  val addOutboundOperation = (apiOperation[Outbound]("addOutbound")
    summary "create a participant news item"
    parameters (bodyParam[Outbound]("body").description("")))

  post("/new", operation(addOutboundOperation)) {

    val body = parsedBody.extract[Outbound]

    outboundService.add(body)
  }

  val getOutboundOperation = (apiOperation[List[Outbound]]("getOutbound")
    summary "retrieve the news posted by an individual participant"
    parameters (pathParam[Long]("id").description("")))

  get("/:id", operation(getOutboundOperation)) {

    val id = params.getOrElse("id", halt(400))

    outboundService.gets(id.toLong)
  }

  val searchOutboundOperation = (apiOperation[List[Long]]("searchOutbound")
    summary "create a participant news item"
    parameters (queryParam[String]("keywords").description("")))

  post("/search", operation(searchOutboundOperation)) {

    val keywords = params.getAs[String]("keywords")

    outboundService.search(keywords)
  }

}
