/*
 * News Feed
 *
 * news feed api
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"
	"newsfeedserver"
)

func main() {
	log.Printf("Server started")

	router := newsfeedserver.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
