/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package info.glennengstrand.resources;

import java.util.List;

import info.glennengstrand.api.Inbound;
import info.glennengstrand.api.Outbound;

public interface InboundApi {
    Inbound addInbound(Inbound body);
    List<Inbound> getInbound(Long id);
}
