/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package info.glennengstrand.resources;

import info.glennengstrand.api.Participant;

public interface ParticipantApi {
      Participant addParticipant(Participant body);
      Participant getParticipant(Long id);

}
