addSbtPlugin("com.eed3si9n"      % "sbt-assembly"        % "0.14.10")
addSbtPlugin("com.lucidchart"    % "sbt-scalafmt"        % "1.14")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "1.6.0")
addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph"% "0.9.2")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker"          % "1.5.0")
