library(party)
l <- read.csv("/home/glenn/git/clojure-news-feed/client/ml/etl/latency.csv")
cc <- ctree_control(maxdepth = 6)
dt <- ctree(cloud ~ `friends.POST` + `outbound.POST` + `participant.POST`, data = l, control = cc)
plot(dt)
dt <- ctree(feed ~ `friends.POST` + `outbound.POST` + `participant.POST`, data = l, control = cc)
plot(dt)
t <- read.csv("/home/glenn/git/clojure-news-feed/client/ml/etl/throughput.csv")
dt <- ctree(cloud ~ `friends.POST` + `outbound.POST` + `participant.POST`, data = t)
plot(dt)
dt <- ctree(feed ~ `friends.POST` + `outbound.POST` + `participant.POST`, data = t)
plot(dt)
