# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Participant(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, link: str=None):
        """
        Participant - a model defined in Swagger

        :param id: The id of this Participant.
        :type id: int
        :param name: The name of this Participant.
        :type name: str
        :param link: The link of this Participant.
        :type link: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'link': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'link': 'link'
        }

        self._id = id
        self._name = name
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'Participant':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The participant of this Participant.
        :rtype: Participant
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """
        Gets the id of this Participant.

        :return: The id of this Participant.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """
        Sets the id of this Participant.

        :param id: The id of this Participant.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """
        Gets the name of this Participant.

        :return: The name of this Participant.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this Participant.

        :param name: The name of this Participant.
        :type name: str
        """

        self._name = name

    @property
    def link(self) -> str:
        """
        Gets the link of this Participant.

        :return: The link of this Participant.
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link: str):
        """
        Sets the link of this Participant.

        :param link: The link of this Participant.
        :type link: str
        """

        self._link = link

