/**
 * News Feed
 * news feed api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: media@glennengstrand.info
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */

package info.glennengstrand.news.model

case class Friend(
  id: Option[Long],
  from: Option[String],
  to: Option[String]) {
  def isValid: Boolean = {
    from match {
      case Some(_) => {
        to match {
          case Some(_) => true
          case None => false
        }
      }
      case None => false
    }
  }
}
