/*
 * News Feed
 *
 * news feed api
 *
 * API version: 1.0.0
 * Contact: media@glennengstrand.info
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package newsfeedserver

type Friend struct {

	Id int64 `json:"id,omitempty"`

	From int64 `json:"from,omitempty"`

	To int64 `json:"to,omitempty"`
}
