{:sql-host "127.0.0.1"
 :sql-db-name "feed"
 :sql-db-user "root"
 :sql-db-password "******"
 :sql-vendor "mysql"
 :nosql-host "localhost"
 :nosql-consistency "one" 
 :nosql-ttl 7776000 
 :cache-host "localhost"
 :messaging-host "localhost"
 :search-host "http://localhost:8983/solr/outbound"}