/**
 * News Feed
 * news feed api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: media@glennengstrand.info
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package info.glennengstrand.resources;

import com.google.inject.Inject;  
import javax.ws.rs.GET;  
import javax.ws.rs.POST;  
import javax.ws.rs.PathParam;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.Consumes;
import javax.ws.rs.core.MediaType;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import info.glennengstrand.api.Participant;
import io.dropwizard.jersey.params.LongParam;

@Path("/participant")
public class ParticipantApi {

   private final ParticipantApiService participantService;
   private static final Logger LOGGER = LoggerFactory.getLogger(ParticipantApi.class);
	
   @Inject
   public ParticipantApi(ParticipantApiService participantService) {
      this.participantService = participantService;
   }
      
   @POST
   @Path("/new")
   @Consumes(MediaType.APPLICATION_JSON)
   @Produces(MediaType.APPLICATION_JSON)
  /**
   * create a new participant
   * a participant is someone who can post news to friends
   * @param body participant to be created (required)
   * @return Participant
   */
   public Participant addParticipant(Participant body) {
      //return participantService.addParticipant(body);
	   return body;
   }
   @GET
   @Path("/{id}")
   @Produces(MediaType.APPLICATION_JSON)
  /**
   * retrieve an individual participant
   * fetch a participant by id
   * @param id uniquely identifies the participant (required)
   * @return Participant
   */
   public Participant getParticipant(@PathParam("id") LongParam id) {
	   LOGGER.debug(String.format("get participant %d", id.get()));
       return participantService.getParticipant(id.get());
   }
   
   public static interface ParticipantApiService {
      Participant addParticipant(Participant body);
      Participant getParticipant(Long id);
   }
}
