/**
 * News Feed
 * news feed api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Eclipse Public License - v 1.0
 *
 * https://www.eclipse.org/legal/epl-v10.html
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package info.glennengstrand.resources;

import com.google.inject.Inject;  
import javax.ws.rs.GET;  
import javax.ws.rs.POST;  
import javax.ws.rs.PathParam;
import javax.ws.rs.QueryParam;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.Consumes;
import javax.ws.rs.core.MediaType;
import java.util.List;
import io.dropwizard.jersey.params.LongParam;

import info.glennengstrand.api.Participant;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Path("/participant")
public class ParticipantApi {

   private static final Logger LOGGER = LoggerFactory.getLogger(ParticipantApi.class);
   private final ParticipantApiService participantService;
	
   @Inject
   public ParticipantApi(ParticipantApiService participantService) {
      this.participantService = participantService;
   }
   @POST
   @Consumes("application/json")
   @Produces("application/json")
  /**
   * create a new participant
   * a participant is someone who can post news to friends
   * @param body participant to be created (required)
   * @return Participant
   */
   public Participant addParticipant( Participant body) {
      return participantService.addParticipant(body);
   }

   public static interface ParticipantApiService {
      Participant addParticipant(Participant body);
      Participant getParticipant(Long id);
   }
}
