/*
 * News Feed
 *
 * news feed api
 *
 * API version: 1.0.0
 * Contact: media@glennengstrand.info
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package newsfeedserver

type Participant struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`
	
	Link string `json:"link,omitempty"`
}
