/*
 * News Feed
 *
 * news feed api
 *
 * API version: 1.0.0
 * Contact: media@glennengstrand.info
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package newsfeedserver

import (
	"time"
)

type Outbound struct {

	From int64 `json:"from,omitempty"`

	Occurred time.Time `json:"occurred,omitempty"`

	Subject string `json:"subject,omitempty"`

	Story string `json:"story,omitempty"`
}
