/**
 * News Feed
 * news feed api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Eclipse Public License - v 1.0
 *
 * https://www.eclipse.org/legal/epl-v10.html
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package info.glennengstrand.resources;

import info.glennengstrand.util.Link;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;


/**
 * API tests for FriendApi
 */
public class FriendApiTest extends NewsFeedTestBase {
    
    @Before
    public void setup() {
    	setupFriendSupport();
    }
    
    /**
     * create a new friendship
     *
     * friends are those participants who receive news
     *
     */
    @Test
    public void addFriendTest() {
        assertTrue(String.format("expected id to be %d but it was %d instead", TEST_ID, friendApi.addFriend(TEST_FROM, friend).getId()), friendApi.addFriend(TEST_FROM, friend).getId() == TEST_ID);
    }
    
    /**
     * retrieve the list of friends for an individual participant
     *
     * fetch participant friends
     *
     */
    @Test
    public void getFriendTest() {
        assertTrue(String.format("expected from to be %d but it was %d instead", TEST_TO, Link.extractId(friendApi.getFriend(TEST_ID).get(0).getTo())), Link.extractId(friendApi.getFriend(TEST_FROM).get(0).getTo()) == TEST_TO);
    }
    
}
