/**
 * News Feed
 * news feed api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Eclipse Public License - v 1.0
 *
 * https://www.eclipse.org/legal/epl-v10.html
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package info.glennengstrand.resources;

import info.glennengstrand.api.Friend;
import org.junit.Test;

/**
 * API tests for FriendApi
 */
public class FriendApiTest {

    private final FriendApi api = null;

    
    /**
     * create a new friendship
     *
     * friends are those participants who receive news
     *
     */
    @Test
    public void addFriendTest() {
        Friend body = null;
        // Friend response = api.addFriend(body);

        // TODO: test validations
    }
    
    /**
     * retrieve the list of friends for an individual participant
     *
     * fetch participant friends
     *
     */
    @Test
    public void getFriendTest() {
        Long id = null;
        // List<Friend> response = api.getFriend(id);

        // TODO: test validations
    }
    
}
