/**
 * News Feed
 * news feed api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Eclipse Public License - v 1.0
 *
 * https://www.eclipse.org/legal/epl-v10.html
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package info.glennengstrand.resources;

import info.glennengstrand.api.Participant;
import org.junit.Test;

/**
 * API tests for ParticipantApi
 */
public class ParticipantApiTest {

    private final ParticipantApi api = null;

    
    /**
     * create a new participant
     *
     * a participant is someone who can post news to friends
     *
     */
    @Test
    public void addParticipantTest() {
        Participant body = null;
        // Participant response = api.addParticipant(body);

        // TODO: test validations
    }
    
    /**
     * retrieve an individual participant
     *
     * fetch a participant by id
     *
     */
    @Test
    public void getParticipantTest() {
        Long id = null;
        // Participant response = api.getParticipant(id);

        // TODO: test validations
    }
    
}
