/**
 * News Feed
 * news feed api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: media@glennengstrand.info
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package info.glennengstrand.api;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Inbound
 */

public class Inbound   {
  private Long from = null;

  private Long to = null;

  private Inbound() {}
  public Inbound ( 
    @JsonProperty("from")
    Long from,
    @JsonProperty("to")
    Long to
    ) {
      this.from = from;
      this.to = to;
    }
    /**
    * Get from
    * @return from
    **/
    @JsonProperty("from")
    @ApiModelProperty(example = "null", value = "")
    public Long getFrom() {
      return from;
    }
    /**
    * Get to
    * @return to
    **/
    @JsonProperty("to")
    @ApiModelProperty(example = "null", value = "")
    public Long getTo() {
      return to;
    }

    @Override
    public boolean equals(java.lang.Object o) {
      if (this == o) {
        return true;
      }
      if (o == null || getClass() != o.getClass()) {
        return false;
      }
      Inbound inbound = (Inbound) o;
      return Objects.equals(this.from, inbound.from) &&
        Objects.equals(this.to, inbound.to);
    }

    @Override
    public int hashCode() {
      return Objects.hash(from, to);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder();
      sb.append("class Inbound {\n");
      
      sb.append("    from: ").append(toIndentedString(from)).append("\n");
      sb.append("    to: ").append(toIndentedString(to)).append("\n");
      sb.append("}");
      return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
      if (o == null) {
        return "null";
      }
      return o.toString().replace("\n", "\n    ");
    }

  public static class InboundBuilder {
    private Long from = null;
    private Long to = null;
    public InboundBuilder withFrom(Long from) {
      this.from = from;
      return this;
    }
    public InboundBuilder withTo(Long to) {
      this.to = to;
      return this;
    }
    public Inbound build() {
      return new Inbound (
        from, 
        to 
      );
    }
  }
}

